services:
  python-executor:
    build:
      context: ./python-secure
      dockerfile: Dockerfile
    networks:
      - code-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "1000:1000"
    restart: unless-stopped

networks:
  code-network:
    driver: bridge